variables:
  IMAGE_NAME: alekseykudr/game2048
  IMAGE_TAG: v1.1


build_image:
  tags:
    - shell-dev
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG