variables:
  IMAGE_NAME: alekseykudr/game2048
  IMAGE_TAG: v1.1

stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - shell-dev
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual

deploy:
  stage: deploy
  image:
    name: devupsen/ansible:6.5.0
  tags:
    - docker
  before_script:
    - export ANSIBLE_CONFIG=ansible/ansible.cfg
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" > /tmp/key && chmod 600 /tmp/key
    - echo "SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
    - cat /tmp/key > ~/.ssh/id_rsa
    - ssh-add /tmp/key
  script:
    - ansible-galaxy install --role-file=ansible/requirements.yml --force
    - ansible-playbook playbook-docker.yml -vvv
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual


