build_image:
  tags:
    - shell-dev
  before_script:
    - docker login gitlab.alkudr.ru:5050
  script:
    - docker build -t gitlab.alkudr.ru:5050/gon/game2048-task .
    - docker push gitlab.alkudr.ru:5050/gon/game2048-task