variables:
  IMAGE_NAME: alekseykudr/game2048
  IMAGE_TAG: v1.1

stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - shell-dev
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  tags:
    - shell-ansible
  before_script:
    - cd /opt/ansible/
    - git clone git@gitlab.alkudr.ru:roles/node16.git
  script:
    - ansible-playbook -i inv_ini game2048-docker.yml

