variables:
  IMAGE_NAME: alekseykudr/game2048
  IMAGE_TAG: v1.1

stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - shell-dev
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  tags:
    - shell-dev
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@192.168.1.70 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 8080:8080 $IMAGE_NAME:$IMAGE_TAG"
