variables:
  IMAGE_NAME: alekseykudr/game2048
  IMAGE_TAG: v1.1

stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - shell-dev
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual

deploy:
  stage: deploy
  tags:
    - shell-ansible
  script:
    - cd /opt/ansible
    - ls
    - ping -—Å 4 app01
    - ansible-playbook -i inv.ini game2048-docker.yml
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual


