variables:
  IMAGE_NAME: alekseykudr/game2048
  IMAGE_TAG: v1.1

stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - shell-dev
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual

deploy:
  stage: deploy
  tags:
    - shell-ansible
  before_script:
    - export ANSIBLE_CONFIG=/opt/ansible/ansible.cfg
    - eval $(ssh-agent -s)
    - whoami
    - chmod -R 600 ~/.ssh
  script:
    - cd /opt/ansible
    - ls
    - ansible-galaxy install --role-file=requirements.yml --force
    - ansible-playbook -i inv.ini game2048-docker.yml -vvv
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual


