version: "3"

services:
  game2048:
    image: alekseykudr/game2048:v1.1
    container_name: game2048
    hostname: game2048
    ports:
      - "8080:8080"
    networks:
      - game2048-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - game2048
    networks:
      - game2048-network


networks:
  game2048-network:
    external: true