apiVersion: v1
kind: Pod
metadata:
  name: game2048-app
  labels:
    app: game2048
spec:
  containers:
    - name: game2048-app
      image: alekseykudr/game2048:v1.1
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
